
class Data:
    BLACK_BUN_NAME = "black bun"
    BLACK_BUN_PRICE = 100
    WHITE_BUN_NAME = "white bun"
    WHITE_BUN_PRICE = 200
    RED_BUN_NAME = "red bun"
    RED_BUN_PRICE = 300
    INGREDIENT_HOT_SAUCE_NAME = "hot sauce"
    INGREDIENT_HOT_SAUCE_PRICE = 100
    INGREDIENT_SOUR_CREAM_NAME = "sour cream"
    INGREDIENT_SOUR_CREAM__PRICE = 200
    INGREDIENT_CILI_SAUCE_NAME = "chili sauce"
    INGREDIENT_CILI_SAUCE_PRICE = 300
    INGREDIENT_CUTLET_NAME = "cutlet"
    INGREDIENT_CUTLET_PRICE = 100
    INGREDIENT_DINOSAUR_NAME = "dinosaur"
    INGREDIENT_DINOSAUR_PRICE = 200
    INGREDIENT_SAUSAGE_NAME = "sausage"
    INGREDIENT_SAUSAGE_PRICE = 300


