from praktikum.ingredient_types import INGREDIENT_TYPE_SAUCE, INGREDIENT_TYPE_FILLING


class TestData:
    BUN_NAME = 'Сhicken'
    BUN_PRICE = 120.7

    INGREDIENT_TYPE = INGREDIENT_TYPE_FILLING
    INGREDIENT_NAME = "Шоколадная"
    INGREDIENT_PRICE = 20.50

    INGREDIENT_TYPE_SAUCE = INGREDIENT_TYPE_SAUCE
    INGREDIENT_NAME_SAUCE = "Томатный"
    INGREDIENT_PRICE_SAUCE = 18
